# See https://github.com/actions/labeler for details
# "dependencies" label for any changes in dependency files
# Add 'repo' label to any root file changes
documentation:
  - examples/**/*
  - README.md

examples:
  - examples/**/*

terraform:
  - "*.tf"
  - modules/**/*

unittests:
  - test/**/*
  - modules/**/test/*

github:
  - .github/**/*
