name: Feature Request
description: Feature request for the Terraform Modules.
title: "[Feature]: "
labels: ["feature", "P1", "terraform-modules"]
assignees: ["brent-anyscale"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new feature.
        Please make sure to search for existing issues before filing a new one.
  - type: textarea
    id: new-feature
    attributes:
      label: What are you looking for?
      description: Please provide a detailed explanation of the new feature request you are looking for.
      placeholder: "Feature request!!"
    validations:
      required: true
  - type: input
    id: which-module
    attributes:
      label: Which module?
      description: "Which module(s) are you having problems with?"
      placeholder: "ex. Root, S3, EFS, IAM, VPC, S3-Policy, SecurityGroup"
  - type: dropdown
    id: blocking_work
    attributes:
      label: Is it blocking work?
      description: Please choose one?
      multiple: false
      options:
        - "no"
        - "yes"
    validations:
      required: true
  - type: dropdown
    id: terraform_version
    attributes:
      label: Terraform version
      description: What version of Terraform are you using?
      multiple: false
      options:
        - 1.3.x (Default)
        - 1.2.x
        - 1.1.x
        - 1.0.x
        - Other
    validations:
      required: false

# - [ ] I searched the [issues](https://github.com/anyscale/terraform-cloudfoundation-modules/issues) and found no similar issues.

### Terraform Module (EFS, IAM, S3, S3-Policy, SecurityGroups, VPC)

### What happened + What you expected to happen (provide screenshots if possible)

### Versions / Dependencies (Terraform, AWS Provider, Modules, etc)

### Reproduction script

### Anything else
