name: Feature Request
description: Feature request for the Terraform Modules.
title: "[Feature]: "
labels: ["feature", "P1", "terraform-modules"]
assignees: ["brent-anyscale"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new feature.
        Please make sure to search for existing issues before filing a new one.
  - type: textarea
    attributes:
      label: What are you looking for?
      description: Please provide a detailed explanation of the new feature request you are looking for.
      placeholder: "Feature request!!"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Which module(s)?
      description: "Please select which module(s) this issue impacts."
      options:
        - label: Root Anyscale Module
        - label: aws-anyscale-efs
        - label: aws-anyscale-iam
        - label: aws-anyscale-s3
        - label: aws-anyscale-s3-policy
        - label: aws-anyscale-securitygroups
        - label: aws-anyscale-vpc
  - type: dropdown
    attributes:
      label: Is it blocking work?
      description: Please choose one?
      multiple: false
      options:
        - "no"
        - "yes"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Terraform version
      description: What version of Terraform are you using?
      multiple: false
      options:
        - 1.3.x (Default)
        - 1.2.x
        - 1.1.x
        - 1.0.x
        - Other
    validations:
      required: false
